import './plugins/price_calculator.js';
import './plugins/crazy_btn.js';
import './plugins/timer.js';
import './plugins/accordion.js';
import './plugins/scroll_line.js';
import './plugins/bookmark.js';
import './plugins/calculator.js';
import './plugins/quiz.js';
import './plugins/mouseevent.js';
